/*
 * Creates a JS file/module from the JSON file with contract metadata
 */

const fs = require('fs');
const process = require('process');

// 0 is the exe (e.g. node), 1 the js file being executed.
const inFile = process.argv[2];
const outFile = process.argv[3];

const jsonStr = fs.readFileSync(inFile);

const outStr =
/* eslint-disable */
`/* 
 * Note: this file was generated by a script. Manual changes may be overwritten !
 * 
 * Contains the ABI definition needed to interact with the contract and other metadata generated by the truffle framework.
 */
/* eslint-disable */
const contract = ${jsonStr}

export default contract;
`;
/* eslint-enable */

fs.writeFileSync(outFile, outStr);
