/* 
 * Note: this file was generated by a script. Manual changes may be overwritten !
 * 
 * Contains the ABI definition needed to interact with the contract and other metadata generated by the truffle framework.
 */
/* eslint-disable */
const contract = {
  "contract_name": "P4PState",
  "abi": [
    {
      "constant": false,
      "inputs": [
        {
          "name": "stateHashes",
          "type": "bytes32[]"
        },
        {
          "name": "boards",
          "type": "bytes32[]"
        }
      ],
      "name": "addGames",
      "outputs": [],
      "payable": false,
      "type": "function"
    }
  ],
  "unlinked_binary": "0x6060604052341561000f57600080fd5b5b60fb8061001e6000396000f300606060405263ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416630c2b4b858114603c575b600080fd5b3415604657600080fd5b60c860046024813581810190830135806020818102016040519081016040528093929190818152602001838360200280828437820191505050505050919080359060200190820180359060200190808060200260200160405190810160405280939291908181526020018383602002808284375094965060ca95505050505050565b005b5b50505600a165627a7a72305820852f6aff785a17e0b88d312dba566e5b8a08f2b633598531045dfe2215efa1190029",
  "networks": {
    "4": {
      "events": {},
      "links": {},
      "address": "0x3e71759b2d0922dacb5921ee3df52e6f91d87e3d",
      "updated_at": 1509935116191
    },
    "1509934429918": {
      "events": {},
      "links": {},
      "address": "0xdcbd8b68055e3b386295c82bb652188100bab590",
      "updated_at": 1509937268790
    }
  },
  "schema_version": "0.0.5",
  "updated_at": 1509937268790
}

export default contract;
